/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pesquisa;

import ConexaoDB.Conectar;
import Utilitarios.LimitaField;
import Utilitarios.Utilitarios;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author PC
 */
public class TelaConhecimentoTransporteEletronico extends javax.swing.JDialog {

    Integer selecionada, valor;
    String sql, ordnar; 
    DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
    DefaultTableCellRenderer centro = new DefaultTableCellRenderer();
    DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
    Utilitarios util = new Utilitarios();
    
  
    public TelaConhecimentoTransporteEletronico() {
        initComponents();
        DefinirFormulario();
        CarregaUnTransporte(util.sDAD_CODIGO.toString());
        SairEsc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlPrincipal = new javax.swing.JPanel();
        jPnlBusca = new javax.swing.JPanel();
        jBtOk = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFldCodigoDeBarras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFldChave = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrincipal = new javax.swing.JTable();
        jBtInserir = new javax.swing.JButton();
        jBtAlterar = new javax.swing.JButton();
        jBtExcluir = new javax.swing.JButton();
        jLblSituacaoChave = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPnlPrincipal.setLayout(new java.awt.CardLayout());

        jPnlBusca.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Conhecimento de Transporte Eletrônico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jBtOk.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtOk.setText("OK");
        jBtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtOkActionPerformed(evt);
            }
        });
        jBtOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtOkKeyPressed(evt);
            }
        });

        jBtCancelar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtCancelar.setText("Fechar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });
        jBtCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtCancelarKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Código de Barras");

        jFldCodigoDeBarras.setDocument(new LimitaField(36, 1)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("*Chave de Acesso");

        jFldChave.setDocument(new LimitaField(44, 2)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Unidades de Transporte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTablePrincipal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "", "Código", "Tipo de Transporte", "Identificação", "Quantidade Rateada", "Quantidade de Unidade de Carga", "Quantidade de Lacres"
            }
        ){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                if(colIndex == 0){
                    return true;
                }else{
                    return false;
                }
                //Disallow the editing of any cell
            };

            Class[] types = new Class [] {

                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class , java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class

            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

        });
        jTablePrincipal.getTableHeader().setResizingAllowed(false);
        jTablePrincipal.getTableHeader().setReorderingAllowed(false);
        jTablePrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePrincipalMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTablePrincipalMouseReleased(evt);
            }
        });
        jTablePrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablePrincipalKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePrincipal);

        jBtInserir.setText("Inserir");
        jBtInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtInserirActionPerformed(evt);
            }
        });
        jBtInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtInserirKeyPressed(evt);
            }
        });

        jBtAlterar.setText("Alterar");
        jBtAlterar.setEnabled(false);
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });
        jBtAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtAlterarKeyPressed(evt);
            }
        });

        jBtExcluir.setText("Excluir");
        jBtExcluir.setEnabled(false);
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });
        jBtExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtExcluirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtInserir)
                .addGap(3, 3, 3)
                .addComponent(jBtAlterar)
                .addGap(3, 3, 3)
                .addComponent(jBtExcluir)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLblSituacaoChave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wrong_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPnlBuscaLayout = new javax.swing.GroupLayout(jPnlBusca);
        jPnlBusca.setLayout(jPnlBuscaLayout);
        jPnlBuscaLayout.setHorizontalGroup(
            jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBuscaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPnlBuscaLayout.createSequentialGroup()
                        .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlBuscaLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jFldChave, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblSituacaoChave))
                            .addGroup(jPnlBuscaLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jFldCodigoDeBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnlBuscaLayout.createSequentialGroup()
                                .addComponent(jBtOk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jBtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 304, Short.MAX_VALUE)))
                .addGap(8, 8, 8))
        );
        jPnlBuscaLayout.setVerticalGroup(
            jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBuscaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFldChave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLblSituacaoChave)))
                .addGap(5, 5, 5)
                .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFldCodigoDeBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtOk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jPnlPrincipal.add(jPnlBusca, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtOkActionPerformed
       
    }//GEN-LAST:event_jBtOkActionPerformed

    private void jBtOkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtOkKeyPressed
        
    }//GEN-LAST:event_jBtOkKeyPressed

    private void jBtInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtInserirActionPerformed
       TelaUnidadeTransporte telaUnTransp = new TelaUnidadeTransporte(util.sDAD_CODIGO.toString(), null, "C", jFldChave.getText(), "1");
       telaUnTransp.setVisible(true);
       CarregaUnTransporte(util.sDAD_CODIGO.toString());
    }//GEN-LAST:event_jBtInserirActionPerformed

    private void jBtInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtInserirKeyPressed
      
    }//GEN-LAST:event_jBtInserirKeyPressed

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        for (int linha = 0; linha < jTablePrincipal.getRowCount(); linha++) {
            if(((boolean)jTablePrincipal.getValueAt(linha, 0)) == true){
                TelaUnidadeTransporte telaUnTransp = new TelaUnidadeTransporte(util.sDAD_CODIGO.toString(), jTablePrincipal.getValueAt(linha, 1).toString(), "C", jFldChave.getText(), "2");
                telaUnTransp.setVisible(true);
            }
        }
        
        CarregaUnTransporte(util.sDAD_CODIGO.toString());
    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jBtAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtAlterarKeyPressed
       
    }//GEN-LAST:event_jBtAlterarKeyPressed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        for (int linha = 0; linha < jTablePrincipal.getRowCount(); linha++) {
            if(((boolean)jTablePrincipal.getValueAt(linha, 0)) == true){
                TelaUnidadeTransporte telaUnTransp = new TelaUnidadeTransporte(util.sDAD_CODIGO.toString(), jTablePrincipal.getValueAt(linha, 1).toString(), "C", jFldChave.getText(), "3");
                telaUnTransp.dispose();
            }
        }
        
        CarregaUnTransporte(util.sDAD_CODIGO.toString());
    }//GEN-LAST:event_jBtExcluirActionPerformed

    private void jBtExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtExcluirKeyPressed
       
    }//GEN-LAST:event_jBtExcluirKeyPressed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jBtCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtCancelarKeyPressed
        
    }//GEN-LAST:event_jBtCancelarKeyPressed

    private void jTablePrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablePrincipalKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            jBtOk.doClick();
        }
    }//GEN-LAST:event_jTablePrincipalKeyPressed

    private void jTablePrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePrincipalMouseClicked

       /* selecionada = jTablePrincipal.getSelectedRow();
        if(evt.getClickCount() == 2){
            if(selecionada == -1){
                return;
            }

            jBtOk.doClick();
            this.dispose();
        }*/
    }//GEN-LAST:event_jTablePrincipalMouseClicked

    private void jTablePrincipalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePrincipalMouseReleased
        int Selecionada = 0;
        for (int linha = 0; linha < jTablePrincipal.getRowCount(); linha++) {
            if(((boolean)jTablePrincipal.getValueAt(linha, 0))){
                Selecionada++;
            }
        }
        
        if(Selecionada == 1){
            jBtExcluir.setEnabled(true);
            jBtAlterar.setEnabled(true);
        }else if(Selecionada >= 2){
            jBtAlterar.setEnabled(false);
        }else if(Selecionada == 0){
            jBtExcluir.setEnabled(false);
            jBtAlterar.setEnabled(false);
        }
    }//GEN-LAST:event_jTablePrincipalMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate=" collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConhecimentoTransporteEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConhecimentoTransporteEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConhecimentoTransporteEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConhecimentoTransporteEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConhecimentoTransporteEletronico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtInserir;
    private javax.swing.JButton jBtOk;
    private javax.swing.JTextField jFldChave;
    private javax.swing.JTextField jFldCodigoDeBarras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblSituacaoChave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlBusca;
    private javax.swing.JPanel jPnlPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrincipal;
    // End of variables declaration//GEN-END:variables

    public void DefinirFormulario() {
        setTitle("Pesquisar");
        setSize(850, 400);
        jPnlPrincipal.setSize(850, 400);
        jPnlBusca.setSize(850, 400);
        setLocationRelativeTo(this);
        setResizable(true);
        setModal(true);
        
        jTablePrincipal.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTablePrincipal.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        for (int col = 0; col < jTablePrincipal.getColumnCount(); col++) {
            jTablePrincipal.getColumnModel().getColumn(col).setHeaderRenderer(new MeuRenderizador());
        }
        
        centro.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        
        
        //Define o tamanho das colunas e posicoes das celulas        
        jTablePrincipal.getColumnModel().getColumn(0).setMinWidth(30);
        jTablePrincipal.getColumnModel().getColumn(0).setMaxWidth(30);

        //Tipo de Transporte
        jTablePrincipal.getColumnModel().getColumn(1).setMinWidth(300);
        jTablePrincipal.getColumnModel().getColumn(1).setMaxWidth(500);
        jTablePrincipal.getColumnModel().getColumn(1).setCellRenderer(esquerda);

        //Identificação
        jTablePrincipal.getColumnModel().getColumn(2).setMinWidth(250);
        jTablePrincipal.getColumnModel().getColumn(2).setMaxWidth(300);
        jTablePrincipal.getColumnModel().getColumn(2).setCellRenderer(esquerda);
        
        //Quantidade Rateada
        jTablePrincipal.getColumnModel().getColumn(3).setMinWidth(300);
        jTablePrincipal.getColumnModel().getColumn(3).setMaxWidth(350);
        jTablePrincipal.getColumnModel().getColumn(3).setCellRenderer(esquerda);
        
        //Quantidade de Unidade de Carga
        jTablePrincipal.getColumnModel().getColumn(4).setMinWidth(300);
        jTablePrincipal.getColumnModel().getColumn(4).setMaxWidth(420);
        jTablePrincipal.getColumnModel().getColumn(4).setCellRenderer(esquerda);
        
        //Quantidade de Lacres
        jTablePrincipal.getColumnModel().getColumn(5).setMinWidth(200);
        jTablePrincipal.getColumnModel().getColumn(5).setMaxWidth(300);
        jTablePrincipal.getColumnModel().getColumn(5).setCellRenderer(esquerda);
                
        //Adiciona as teclas de atalho  ALT + para os seguintes botões
        jBtOk.setMnemonic(java.awt.event.KeyEvent.VK_O);
        jBtCancelar.setMnemonic(java.awt.event.KeyEvent.VK_C);

    }
    
    
    public void LimpaTabela() {
        DefaultTableModel tableModel = (DefaultTableModel) jTablePrincipal.getModel();
        tableModel.setNumRows(0);
    }
    
    
    public void CarregaUnTransporte(String Dados_codigo) {
        try {
            Conectar.ConectarBD();
            LimpaTabela();
            Conectar.result = Conectar.stam.executeQuery("SELECT * FROM MDFE_UN_TRANSPORTE WHERE DAD_CODIGO = '" +Dados_codigo+"' ");
            DefaultTableModel dtm = (DefaultTableModel) jTablePrincipal.getModel();
            while (Conectar.result.next()) {
                dtm.addRow(new Object[]{
                    false,
                    Conectar.result.getString("COD_TRANSP"),
                    Conectar.result.getString("DAD_CODIGO"),
                    Conectar.result.getString("TP_UN_TRANS"),
                    Conectar.result.getString("ID_UN_TRANS"),
                    Conectar.result.getString("QTD_RAT_TRANS"),
                    Conectar.result.getString("TP_DOC"),
                    Conectar.result.getString("QTD_CARGA"),
                    Conectar.result.getString("QTD_LACRE")                    
                });
            }
            Conectar.DesconectarBD();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao carregar CarregaUnTransporte na tabela...\n" + e.getLocalizedMessage());
        }
    }

    
    //Evento para sair da tela com a tecla esc
    //Chamar evento no construtor principal da classe
    public void SairEsc() {
        KeyStroke ks = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, true);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(ks, "esc");
        getRootPane().getActionMap().put("esc", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if(jPnlBusca.isVisible() == true){
                    dispose();
                }
            }
        });
    }
    
    /**
     * Classe que implementa o método abstrato TableCellRenderer para poder fazer a troca de cor de fundo e fonte
     * do cabeçalho da tabela. 
     */
    private class MeuRenderizador extends JLabel implements TableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int rowIndex, int vColIndex) {

            table.getTableHeader().setBackground(Color.BLUE);
            table.getTableHeader().setOpaque(false);
            //table.getTableHeader().setFont(new Font("Dialog", 11, Font.BOLD));
            setBorder(new LineBorder(Color.WHITE, 1, true));
            setForeground(Color.WHITE);
            setFont(getFont().deriveFont(Font.BOLD));
            setHorizontalAlignment(SwingConstants.LEFT);

            setText(value.toString());

            return this;
        }
    }
    
}
