/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pesquisa;

import ConexaoDB.Conectar;
import Utilitarios.LimitaField;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author PC
 */
public class TelaBuscaPlanoDeContas extends javax.swing.JDialog {

    /**
     * Creates new form TelaBuscaPlanoDeContas
     */
    public Integer iCOD  = 0;
    public String  sDESC = "";
    Integer selecionada, valor;
    String sql, ordnar; 
    DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
    DefaultTableCellRenderer centro = new DefaultTableCellRenderer();
    DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
    
    public TelaBuscaPlanoDeContas() {
        initComponents();
        DefinirFormulario();
        CarregaTudoPlaCon();
        SairEsc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlPrincipal = new javax.swing.JPanel();
        jPnlBusca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFldBuscaPlaCon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlanoDeConta = new javax.swing.JTable();
        jBtOk = new javax.swing.JButton();
        jBtPrimeiro = new javax.swing.JButton();
        jBtAnterior = new javax.swing.JButton();
        jBtProximo = new javax.swing.JButton();
        jBtUltimo = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa");

        jPnlPrincipal.setLayout(new java.awt.CardLayout());

        jPnlBusca.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Informe");
        jPnlBusca.add(jLabel1);
        jLabel1.setBounds(20, 0, 140, 30);

        jFldBuscaPlaCon.setDocument(new LimitaField(100, 0)
        );
        jFldBuscaPlaCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFldBuscaPlaConActionPerformed(evt);
            }
        });
        jFldBuscaPlaCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFldBuscaPlaConKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFldBuscaPlaConKeyReleased(evt);
            }
        });
        jPnlBusca.add(jFldBuscaPlaCon);
        jFldBuscaPlaCon.setBounds(20, 20, 390, 25);

        jTablePlanoDeConta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTablePlanoDeConta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Código", "Máscara", "Plano de Contas"
            }
        ){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            };

        });
        jTablePlanoDeConta.getTableHeader().setResizingAllowed(false);
        jTablePlanoDeConta.getTableHeader().setReorderingAllowed(false);
        jTablePlanoDeConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePlanoDeContaMouseClicked(evt);
            }
        });
        jTablePlanoDeConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablePlanoDeContaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePlanoDeConta);

        jPnlBusca.add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 680, 230);

        jBtOk.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtOk.setText("OK");
        jBtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtOkActionPerformed(evt);
            }
        });
        jBtOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtOkKeyPressed(evt);
            }
        });
        jPnlBusca.add(jBtOk);
        jBtOk.setBounds(20, 300, 90, 30);

        jBtPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/first-icon.png"))); // NOI18N
        jBtPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPrimeiroActionPerformed(evt);
            }
        });
        jBtPrimeiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtPrimeiroKeyPressed(evt);
            }
        });
        jPnlBusca.add(jBtPrimeiro);
        jBtPrimeiro.setBounds(200, 300, 71, 30);

        jBtAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/previous-icon.png"))); // NOI18N
        jBtAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAnteriorActionPerformed(evt);
            }
        });
        jBtAnterior.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtAnteriorKeyPressed(evt);
            }
        });
        jPnlBusca.add(jBtAnterior);
        jBtAnterior.setBounds(270, 300, 71, 30);

        jBtProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/next-icon.png"))); // NOI18N
        jBtProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtProximoActionPerformed(evt);
            }
        });
        jBtProximo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtProximoKeyPressed(evt);
            }
        });
        jPnlBusca.add(jBtProximo);
        jBtProximo.setBounds(340, 300, 71, 30);

        jBtUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/last-icon.png"))); // NOI18N
        jBtUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtUltimoActionPerformed(evt);
            }
        });
        jBtUltimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtUltimoKeyPressed(evt);
            }
        });
        jPnlBusca.add(jBtUltimo);
        jBtUltimo.setBounds(410, 300, 71, 30);

        jBtCancelar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtCancelar.setText("Cancelar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });
        jBtCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtCancelarKeyPressed(evt);
            }
        });
        jPnlBusca.add(jBtCancelar);
        jBtCancelar.setBounds(560, 300, 90, 30);

        jPnlPrincipal.add(jPnlBusca, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFldBuscaPlaConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFldBuscaPlaConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldBuscaPlaConActionPerformed

    private void jFldBuscaPlaConKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldBuscaPlaConKeyReleased
        BuscaPlano(jFldBuscaPlaCon.getText());
    }//GEN-LAST:event_jFldBuscaPlaConKeyReleased

    private void jTablePlanoDeContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePlanoDeContaMouseClicked
        selecionada = jTablePlanoDeConta.getSelectedRow();
        if(evt.getClickCount() == 2){
            if(selecionada == -1){
                return;
            }
            
            jBtOk.doClick();
          
        }

    }//GEN-LAST:event_jTablePlanoDeContaMouseClicked

    private void jBtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtOkActionPerformed
        selecionada = jTablePlanoDeConta.getSelectedRow();
        iCOD  = Integer.parseInt(jTablePlanoDeConta.getValueAt(selecionada, 0).toString());
        sDESC = jTablePlanoDeConta.getValueAt(selecionada, 2).toString();
        this.dispose();
    }//GEN-LAST:event_jBtOkActionPerformed

    private void jBtPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPrimeiroActionPerformed
        //Se o numero de linhas da tabela for 0
        if(jTablePlanoDeConta.getRowCount() > 0){
            //Foca a barra de rolagem
            jScrollPane1.requestFocus();
            //Foca na tabela
            jTablePlanoDeConta.requestFocus();
            //Seta a value da barra de rolagem para 1
            jScrollPane1.getVerticalScrollBar().setValue(1);
            //seleciona a primeira linha
            jTablePlanoDeConta.addRowSelectionInterval(0, 0);
            //habilita e desablita dos respectivos botões
            jBtPrimeiro.setEnabled(false);
            jBtAnterior.setEnabled(false);
            jBtProximo.setEnabled(true);
            jBtUltimo.setEnabled(true);
        }
    }//GEN-LAST:event_jBtPrimeiroActionPerformed

    private void jBtAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAnteriorActionPerformed
        selecionada = jTablePlanoDeConta.getSelectedRow();
        //Verifica se a tabela possui mais de 0 linhas
        if(jTablePlanoDeConta.getRowCount() > 0){
            //se a selecionada for diferente de -1  e 0
            if(selecionada != -1 && selecionada != 0){
                //Foca a barra de rolagem
                jScrollPane1.requestFocus();
                //Seleciona a linha anterior
                jTablePlanoDeConta.setRowSelectionInterval(selecionada -1, selecionada -1);
                //Seta a value da barra de rolagem para acompanhar a linha selecionada
                jScrollPane1.getVerticalScrollBar().setValue(jTablePlanoDeConta.getRowHeight() * jTablePlanoDeConta.getSelectedRow());
                jBtPrimeiro.setEnabled(true);
                jBtAnterior.setEnabled(true);
                jBtProximo.setEnabled(true);
                jBtUltimo.setEnabled(true);
                
                //Se a linha selecionada for igual a zero
            }else if(selecionada == 0){
                //seta as linhas e a os botoes
                jTablePlanoDeConta.setRowSelectionInterval(0, 0);
                jBtPrimeiro.setEnabled(false);
                jBtAnterior.setEnabled(false);
                jBtProximo.setEnabled(true);
                jBtUltimo.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jBtAnteriorActionPerformed

    private void jBtProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtProximoActionPerformed
        selecionada = jTablePlanoDeConta.getSelectedRow();
        //Se o numeros de linhas da tabela for maior que zero
        if(jTablePlanoDeConta.getRowCount() > 0){
            //Se a linha selecionada for diferente de -1 e do total de linhas - 1
            if(selecionada != -1 && selecionada != jTablePlanoDeConta.getRowCount() -1){
                //Foca na barra de rolagem da tabela
                jScrollPane1.requestFocus();
                //Selecionada a proxima linha
                jTablePlanoDeConta.setRowSelectionInterval(selecionada + 1, selecionada + 1);
                //Seta a value da barra de rolagem para que acompanhe a linha selecionada
                jScrollPane1.getVerticalScrollBar().setValue(jTablePlanoDeConta.getRowHeight() * jTablePlanoDeConta.getSelectedRow());
                jBtPrimeiro.setEnabled(true);
                jBtAnterior.setEnabled(true);
                jBtProximo.setEnabled(true);
                jBtUltimo.setEnabled(true);
                //Se a linha selecionada tiver o mesmo valor do total de linhas da tabela -1
            }else if(selecionada == jTablePlanoDeConta.getRowCount() -1){
                //selecionada a ultima linha
                jTablePlanoDeConta.setRowSelectionInterval(jTablePlanoDeConta.getRowCount() -1, jTablePlanoDeConta.getRowCount() -1);
                jBtPrimeiro.setEnabled(true);
                jBtAnterior.setEnabled(true);
                jBtProximo.setEnabled(false);
                jBtUltimo.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jBtProximoActionPerformed

    private void jBtUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtUltimoActionPerformed
        selecionada = jTablePlanoDeConta.getSelectedRow();
        //Se o total de linhas da tabela for maior que 0
        if(jTablePlanoDeConta.getRowCount() > 0){
            //Seleciona a ultima linha
            jTablePlanoDeConta.setRowSelectionInterval(jTablePlanoDeConta.getRowCount() - 1, jTablePlanoDeConta.getRowCount() -1);
            //Seta a value da barra de rolagem para acompanhar a linha selecionada
            jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
            jBtPrimeiro.setEnabled(true);
            jBtAnterior.setEnabled(true);
            jBtProximo.setEnabled(false);
            jBtUltimo.setEnabled(false);
        }
    }//GEN-LAST:event_jBtUltimoActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jTablePlanoDeContaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablePlanoDeContaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            jBtOk.doClick();
        }
    }//GEN-LAST:event_jTablePlanoDeContaKeyPressed

    private void jBtCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtCancelarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            jBtCancelar.doClick();
        }
        
        if(evt.getKeyCode() == evt.VK_RIGHT){
            jBtOk.requestFocus();
        }
        
        if(evt.getKeyCode() == evt.VK_LEFT){
            jBtUltimo.requestFocus();
        }
    }//GEN-LAST:event_jBtCancelarKeyPressed

    private void jFldBuscaPlaConKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldBuscaPlaConKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(jTablePlanoDeConta.getRowCount() > 0){
                jTablePlanoDeConta.requestFocus();
                jTablePlanoDeConta.addRowSelectionInterval(0, 0);
            }
        }
    }//GEN-LAST:event_jFldBuscaPlaConKeyPressed

    private void jBtOkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtOkKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            jBtOk.doClick();
        }
        
        if(evt.getKeyCode() == evt.VK_RIGHT){
            jBtPrimeiro.requestFocus();
        }
        
        if(evt.getKeyCode() == evt.VK_LEFT){
            jBtCancelar.requestFocus();
        }
    }//GEN-LAST:event_jBtOkKeyPressed

    private void jBtUltimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtUltimoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            jBtUltimo.doClick();
        }
        
        if(evt.getKeyCode() == evt.VK_RIGHT){
            jBtCancelar.requestFocus();
        }
        
        if(evt.getKeyCode() == evt.VK_LEFT){
            jBtProximo.requestFocus();
        }

    }//GEN-LAST:event_jBtUltimoKeyPressed

    private void jBtProximoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtProximoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            jBtProximo.doClick();
        }
        
        if(evt.getKeyCode() == evt.VK_RIGHT){
            jBtUltimo.requestFocus();
        }
        
        if(evt.getKeyCode() == evt.VK_LEFT){
            jBtAnterior.requestFocus();
        }
    }//GEN-LAST:event_jBtProximoKeyPressed

    private void jBtAnteriorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtAnteriorKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            jBtAnterior.doClick();
        }
        
        if(evt.getKeyCode() == evt.VK_RIGHT){
            jBtProximo.requestFocus();
        }
        
        if(evt.getKeyCode() == evt.VK_LEFT){
            jBtPrimeiro.requestFocus();
        }
    }//GEN-LAST:event_jBtAnteriorKeyPressed

    private void jBtPrimeiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtPrimeiroKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            jBtPrimeiro.doClick();
        }
        
        if(evt.getKeyCode() == evt.VK_RIGHT){
            jBtAnterior.requestFocus();
        }
        
        if(evt.getKeyCode() == evt.VK_LEFT){
            jBtOk.requestFocus();
        }
    }//GEN-LAST:event_jBtPrimeiroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaPlanoDeContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaPlanoDeContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaPlanoDeContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaPlanoDeContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscaPlanoDeContas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAnterior;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtOk;
    private javax.swing.JButton jBtPrimeiro;
    private javax.swing.JButton jBtProximo;
    private javax.swing.JButton jBtUltimo;
    private javax.swing.JTextField jFldBuscaPlaCon;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPnlBusca;
    public javax.swing.JPanel jPnlPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlanoDeConta;
    // End of variables declaration//GEN-END:variables

    
    public void DefinirFormulario() {
        setTitle("Pesquisar");
        setSize(685, 370);
        jPnlPrincipal.setSize(685, 370);
        jPnlBusca.setSize(685,370);
        jPnlBusca.setVisible(true);
        setLocationRelativeTo(this);
        setResizable(false);
        setModal(true);
        
        jTablePlanoDeConta.setAutoResizeMode(jTablePlanoDeConta.AUTO_RESIZE_OFF);
        jTablePlanoDeConta.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        for (int col = 0; col < jTablePlanoDeConta.getColumnCount(); col++) {
            jTablePlanoDeConta.getColumnModel().getColumn(col).setHeaderRenderer(new MeuRenderizador());
        }
        
        centro.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);

        jTablePlanoDeConta.getColumnModel().getColumn(0).setMinWidth(60);
        jTablePlanoDeConta.getColumnModel().getColumn(0).setMaxWidth(60);
        jTablePlanoDeConta.getColumnModel().getColumn(0).setCellRenderer(centro);

        jTablePlanoDeConta.getColumnModel().getColumn(1).setMinWidth(200);
        jTablePlanoDeConta.getColumnModel().getColumn(1).setMaxWidth(200);
        jTablePlanoDeConta.getColumnModel().getColumn(1).setCellRenderer(esquerda);

        jTablePlanoDeConta.getColumnModel().getColumn(2).setMinWidth(400);
        jTablePlanoDeConta.getColumnModel().getColumn(2).setMaxWidth(400);
        jTablePlanoDeConta.getColumnModel().getColumn(2).setCellRenderer(esquerda);
        
        //Adiciona as teclas de atalho  ALT + para os seguintes botões
        jBtOk.setMnemonic(java.awt.event.KeyEvent.VK_O);
        jBtCancelar.setMnemonic(java.awt.event.KeyEvent.VK_C);

    }

    public void LimpaTabela() {
        DefaultTableModel tableModel = (DefaultTableModel) jTablePlanoDeConta.getModel();
        tableModel.setNumRows(0);
    }

    public void CarregaTudoPlaCon() {
        try {
            LimpaTabela();
            Conectar.ConectarBD();
            javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTablePlanoDeConta.getModel();
            Conectar.result = Conectar.stam.executeQuery("select * from TABPLACON where RGEVENTO <> '3'");
            while (Conectar.result.next()) {
                dtm.addRow(new Object[]{
                    Conectar.result.getInt("CODPLAN"),
                    Conectar.result.getString("MASCPLAN"),
                    Conectar.result.getString("DESCPLAN"),});
            }
            Conectar.DesconectarBD();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error... " + e.getLocalizedMessage());
        }

    }
    
    

    public void BuscaPlano(String descplan) {
        try {
            sql = "";
            if (!"".equals(descplan)) {
                sql = "where DESCPLAN like '%"  + descplan + "%'";
            } else if ("".equals(descplan)) {
                sql = "where DESCPLAN is not null";
            }

            LimpaTabela();
            Conectar.ConectarBD();
            javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTablePlanoDeConta.getModel();
            Conectar.result = Conectar.stam.executeQuery("select * from TABPLACON " + sql + " and RGEVENTO <> '3'");
            while (Conectar.result.next()) {
                dtm.addRow(new Object[]{
                    Conectar.result.getInt("CODPLAN"),
                    Conectar.result.getString("MASCPLAN"),
                    Conectar.result.getString("DESCPLAN"),});
            }
            Conectar.DesconectarBD();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error... \n" + e.getLocalizedMessage());
        }
    }
    
    //Evento para sair da tela com a tecla esc
    //Chamar evento no construtor principal da classe
    public void SairEsc() {
        KeyStroke ks = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, true);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(ks, "esc");
        getRootPane().getActionMap().put("esc", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if(jPnlBusca.isVisible() == true){
                    dispose();
                }
            }
        });
    }
    
    /**
     * Classe que implementa o método abstrato TableCellRenderer para poder fazer a troca de cor de fundo e fonte
     * do cabeçalho da tabela. 
     */
    private class MeuRenderizador extends JLabel implements TableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int rowIndex, int vColIndex) {

            table.getTableHeader().setBackground(Color.BLUE);
            //table.getTableHeader().setFont(new Font("Dialog", 11, Font.BOLD));
            setOpaque(false);
            setBorder(new LineBorder(Color.WHITE, 1, true));
            setForeground(Color.WHITE);
            setFont(getFont().deriveFont(Font.BOLD));
            setHorizontalAlignment(SwingConstants.LEFT);

            setText(value.toString());

            return this;
        }
    }

}
