/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastro;

import ClassesFirebird.Tabusu;
import ConexaoDB.Conectar;
import Utilitarios.LimitaField;
import Utilitarios.Utilitarios;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

public class TelaTerminalDescarregamento extends javax.swing.JInternalFrame {

    public Integer codmax, selecionada;
    String sql, ordnar, situacao, tag_acao;
    DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
    DefaultTableCellRenderer centro = new DefaultTableCellRenderer();
    DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
    Utilitarios util = new Utilitarios();
    Tabusu tabusu = new Tabusu();
    
    public TelaTerminalDescarregamento() {
        initComponents();
        DefinirFormulario();
        CarregaTudo();
        SairEsc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlPrincipal = new javax.swing.JPanel();
        jPnlBusca = new javax.swing.JPanel();
        jLblBusca = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCmbBxOrdem = new javax.swing.JComboBox<>();
        jFldBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrincipal = new javax.swing.JTable();
        jPnlBotao = new javax.swing.JPanel();
        jBtPrimeiro = new javax.swing.JButton();
        jBtAnterior = new javax.swing.JButton();
        jBtProximo = new javax.swing.JButton();
        jBtUltimo = new javax.swing.JButton();
        jBtInserir = new javax.swing.JButton();
        jBtAlterar = new javax.swing.JButton();
        jBtExcluir = new javax.swing.JButton();
        jCmbBxBusca = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPnlEdit = new javax.swing.JPanel();
        jPnlNorte = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jFldCodigo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jFldCodTerminal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jFldNomeTerminal = new javax.swing.JTextField();
        jPnlSul = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();
        jBtGravar = new javax.swing.JButton();
        jLblAcao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPnlPrincipal.setLayout(new java.awt.CardLayout());

        jLblBusca.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLblBusca.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Busca por:");

        jCmbBxOrdem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCmbBxOrdem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome" }));
        jCmbBxOrdem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbBxOrdemItemStateChanged(evt);
            }
        });
        jCmbBxOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBxOrdemActionPerformed(evt);
            }
        });
        jCmbBxOrdem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbBxOrdemKeyPressed(evt);
            }
        });

        jFldBusca.setDocument(new LimitaField(100, 0)
        );
        jFldBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFldBuscaActionPerformed(evt);
            }
        });
        jFldBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFldBuscaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFldBuscaKeyReleased(evt);
            }
        });

        jTablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Código", "Cód. Terminal", "Nome do Terminal de Descarregamento", "Cód. Usuário", "Usuário", "Data", "Evento"
            }
        ){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            };

        });
        jTablePrincipal.getTableHeader().setResizingAllowed(false);
        jTablePrincipal.getTableHeader().setReorderingAllowed(false);
        jTablePrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePrincipalMouseClicked(evt);
            }
        });
        jTablePrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablePrincipalKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePrincipal);

        jPnlBotao.setPreferredSize(new java.awt.Dimension(580, 44));
        jPnlBotao.setLayout(new java.awt.GridLayout(1, 0));

        jBtPrimeiro.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Primeiro.png"))); // NOI18N
        jBtPrimeiro.setText("Primeiro");
        jBtPrimeiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtPrimeiro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtPrimeiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPrimeiroActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtPrimeiro);

        jBtAnterior.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Anterior.png"))); // NOI18N
        jBtAnterior.setText("Anterior");
        jBtAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtAnterior.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAnteriorActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtAnterior);

        jBtProximo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Proximo.png"))); // NOI18N
        jBtProximo.setText("Próximo");
        jBtProximo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtProximo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtProximo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtProximoActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtProximo);

        jBtUltimo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ultimo.png"))); // NOI18N
        jBtUltimo.setText("Último");
        jBtUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtUltimo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtUltimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtUltimoActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtUltimo);

        jBtInserir.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file_add.png"))); // NOI18N
        jBtInserir.setText("Inserir");
        jBtInserir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtInserir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtInserir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtInserirActionPerformed(evt);
            }
        });
        jBtInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtInserirKeyPressed(evt);
            }
        });
        jPnlBotao.add(jBtInserir);

        jBtAlterar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/text_edit.png"))); // NOI18N
        jBtAlterar.setText("Alterar");
        jBtAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtAlterar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtAlterar);

        jBtExcluir.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/deletar.png"))); // NOI18N
        jBtExcluir.setText("Excluir");
        jBtExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtExcluir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtExcluir);

        jCmbBxBusca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCmbBxBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "Cod. Terminal" }));
        jCmbBxBusca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbBxBuscaItemStateChanged(evt);
            }
        });
        jCmbBxBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBxBuscaActionPerformed(evt);
            }
        });
        jCmbBxBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbBxBuscaKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Ordem:");

        javax.swing.GroupLayout jPnlBuscaLayout = new javax.swing.GroupLayout(jPnlBusca);
        jPnlBusca.setLayout(jPnlBuscaLayout);
        jPnlBuscaLayout.setHorizontalGroup(
            jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBuscaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlBuscaLayout.createSequentialGroup()
                        .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbBxBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbBxOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(10, 10, 10))
            .addGroup(jPnlBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlBuscaLayout.setVerticalGroup(
            jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBuscaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlBuscaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbBxBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbBxOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPnlBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPnlPrincipal.add(jPnlBusca, "card2");

        jPnlEdit.setLayout(new java.awt.BorderLayout());

        jPnlNorte.setPreferredSize(new java.awt.Dimension(560, 200));
        jPnlNorte.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Código");
        jPnlNorte.add(jLabel5);
        jLabel5.setBounds(10, 0, 34, 30);

        jFldCodigo.setEditable(false);
        jFldCodigo.setBackground(new java.awt.Color(255, 255, 204));
        jFldCodigo.setFocusable(false);
        jFldCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFldCodigoFocusLost(evt);
            }
        });
        jFldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFldCodigoActionPerformed(evt);
            }
        });
        jFldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFldCodigoKeyPressed(evt);
            }
        });
        jPnlNorte.add(jFldCodigo);
        jFldCodigo.setBounds(10, 20, 90, 25);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("Código do Terminal");
        jLabel19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel19KeyPressed(evt);
            }
        });
        jPnlNorte.add(jLabel19);
        jLabel19.setBounds(10, 50, 150, 30);

        jFldCodTerminal.setDocument(new LimitaField(8, 1));
        jFldCodTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFldCodTerminalActionPerformed(evt);
            }
        });
        jFldCodTerminal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFldCodTerminalKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFldCodTerminalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFldCodTerminalKeyReleased(evt);
            }
        });
        jPnlNorte.add(jFldCodTerminal);
        jFldCodTerminal.setBounds(10, 70, 90, 25);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("Nome do Terminal");
        jLabel18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel18KeyPressed(evt);
            }
        });
        jPnlNorte.add(jLabel18);
        jLabel18.setBounds(140, 50, 140, 30);

        jFldNomeTerminal.setDocument(new LimitaField(60, 0));
        jFldNomeTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFldNomeTerminalActionPerformed(evt);
            }
        });
        jFldNomeTerminal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFldNomeTerminalKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFldNomeTerminalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFldNomeTerminalKeyReleased(evt);
            }
        });
        jPnlNorte.add(jFldNomeTerminal);
        jFldNomeTerminal.setBounds(140, 70, 430, 25);

        jPnlEdit.add(jPnlNorte, java.awt.BorderLayout.NORTH);

        jPnlSul.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPnlSul.setPreferredSize(new java.awt.Dimension(0, 60));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton10.setText("Inserir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jBtCancelar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtCancelar.setText("Cancelar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });
        jBtCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtCancelarKeyPressed(evt);
            }
        });

        jBtGravar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ok-icon.png"))); // NOI18N
        jBtGravar.setText("Gravar");
        jBtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGravarActionPerformed(evt);
            }
        });
        jBtGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtGravarKeyPressed(evt);
            }
        });

        jLblAcao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblAcao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblAcao.setText("jLabel6");
        jLblAcao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPnlSulLayout = new javax.swing.GroupLayout(jPnlSul);
        jPnlSul.setLayout(jPnlSulLayout);
        jPnlSulLayout.setHorizontalGroup(
            jPnlSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSulLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPnlSulLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jBtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jLblAcao, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(130, 130, 130)
                .addComponent(jBtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPnlSulLayout.setVerticalGroup(
            jPnlSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSulLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPnlSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblAcao)
                        .addComponent(jBtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(260, 260, 260)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPnlEdit.add(jPnlSul, java.awt.BorderLayout.SOUTH);

        jPnlPrincipal.add(jPnlEdit, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbBxOrdemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbBxOrdemItemStateChanged
        BuscaParametro(jFldBusca.getText());
    }//GEN-LAST:event_jCmbBxOrdemItemStateChanged

    private void jCmbBxOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBxOrdemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbBxOrdemActionPerformed

    private void jCmbBxOrdemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbBxOrdemKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (jTablePrincipal.getRowCount() > 0) {
                jTablePrincipal.requestFocus();
                jTablePrincipal.addRowSelectionInterval(0, 0);
            } else {
                jBtInserir.requestFocus();
            }
        }
    }//GEN-LAST:event_jCmbBxOrdemKeyPressed

    private void jFldBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFldBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldBuscaActionPerformed

    private void jFldBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldBuscaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jCmbBxOrdem.requestFocus();
        }
    }//GEN-LAST:event_jFldBuscaKeyPressed

    private void jFldBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldBuscaKeyReleased
    }//GEN-LAST:event_jFldBuscaKeyReleased

    private void jTablePrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePrincipalMouseClicked
        selecionada = jTablePrincipal.getSelectedRow();
        if (evt.getClickCount() == 2) {
            if (selecionada == -1) {
                return;
            }
            jBtAlterar.doClick();

        }
    }//GEN-LAST:event_jTablePrincipalMouseClicked

    private void jTablePrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablePrincipalKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            selecionada = jTablePrincipal.getSelectedRow();
            jBtAlterar.doClick();
        }
    }//GEN-LAST:event_jTablePrincipalKeyPressed

    private void jBtInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtInserirActionPerformed
        //        if(util.VerificarPermissao("01.01.01", tabusu.getCodigo()) == true){
            tag_acao = "1";
            jLblAcao.setText("Inserir");
            LimpaField();
            BuscaCodMax();
            jPnlBusca.setVisible(false);
            jPnlEdit.setVisible(true);
            jFldCodTerminal.requestFocus();
            //      }else{
            //        JOptionPane.showMessageDialog(null, "Usuário não habilitado para este tipo de operação!");
            //  }
    }//GEN-LAST:event_jBtInserirActionPerformed

    private void jBtInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtInserirKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jBtInserir.doClick();
        }
    }//GEN-LAST:event_jBtInserirKeyPressed

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        //    if(util.VerificarPermissao("01.01.02", tabusu.getCodigo()) == true){
            if (selecionada != -1 && jTablePrincipal.getRowCount() > 0) {
                jLblAcao.setText("Alterar");
                LimpaField();
                jPnlBusca.setVisible(false);
                jPnlEdit.setVisible(true);
                tag_acao = "2";
                CarregaCampoEdit(jTablePrincipal.getValueAt(selecionada, 0).toString());
                jFldCodTerminal.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum terminal de descarregamento selecionado");
            }
            //  }else{
            //    JOptionPane.showMessageDialog(null, "Usuário não habilitado para este tipo de operação!");
            //}
    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        //if (util.VerificarPermissao("01.01.03", tabusu.getCodigo()) == true) {
            if (selecionada != -1 && jTablePrincipal.getRowCount() > 0) {
                jLblAcao.setText("Excluir");
                LimpaField();
                jPnlBusca.setVisible(false);
                jPnlEdit.setVisible(true);
                tag_acao = "3";
                jFldCodTerminal.requestFocus();
                CarregaCampoEdit(jTablePrincipal.getValueAt(selecionada, 0).toString());
                int option = JOptionPane.showConfirmDialog(null, "Confirma Exclusão do Registro", "Confirmação", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    jBtGravar.doClick();
                } else if (option == JOptionPane.NO_OPTION) {
                    jBtCancelar.doClick();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum terminal de descarregamento selecionado");
            }
            // } else {
            //   JOptionPane.showMessageDialog(null, "Usuário não habilitado para este tipo de operação!");
            //}
    }//GEN-LAST:event_jBtExcluirActionPerformed

    private void jBtUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtUltimoActionPerformed
        selecionada = jTablePrincipal.getSelectedRow();
        //Se o total de linhas da tabela for maior que 0
        if (jTablePrincipal.getRowCount() > 0) {
            //Seleciona a ultima linha
            jTablePrincipal.setRowSelectionInterval(jTablePrincipal.getRowCount() - 1, jTablePrincipal.getRowCount() - 1);
            //Seta a value da barra de rolagem para acompanhar a linha selecionada
            jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
            jBtPrimeiro.setEnabled(true);
            jBtAnterior.setEnabled(true);
            jBtProximo.setEnabled(false);
            jBtUltimo.setEnabled(false);
        }
    }//GEN-LAST:event_jBtUltimoActionPerformed

    private void jBtProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtProximoActionPerformed
        selecionada = jTablePrincipal.getSelectedRow();
        //Se o numeros de linhas da tabela for maior que zero
        if (jTablePrincipal.getRowCount() > 0) {
            //Se a linha selecionada for diferente de -1 e do total de linhas - 1
            if (selecionada != -1 && selecionada != jTablePrincipal.getRowCount() - 1) {
                //Foca na barra de rolagem da tabela
                jScrollPane1.requestFocus();
                //Selecionada a proxima linha
                jTablePrincipal.setRowSelectionInterval(selecionada + 1, selecionada + 1);
                //Seta a value da barra de rolagem para que acompanhe a linha selecionada
                jScrollPane1.getVerticalScrollBar().setValue(jTablePrincipal.getRowHeight() * jTablePrincipal.getSelectedRow());
                jBtPrimeiro.setEnabled(true);
                jBtAnterior.setEnabled(true);
                jBtProximo.setEnabled(true);
                jBtUltimo.setEnabled(true);
                //Se a linha selecionada tiver o mesmo valor do total de linhas da tabela -1
            } else if (selecionada == jTablePrincipal.getRowCount() - 1) {
                //selecionada a ultima linha
                jTablePrincipal.setRowSelectionInterval(jTablePrincipal.getRowCount() - 1, jTablePrincipal.getRowCount() - 1);
                jBtPrimeiro.setEnabled(true);
                jBtAnterior.setEnabled(true);
                jBtProximo.setEnabled(false);
                jBtUltimo.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jBtProximoActionPerformed

    private void jBtAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAnteriorActionPerformed
        selecionada = jTablePrincipal.getSelectedRow();
        //Verifica se a tabela possui mais de 0 linhas
        if (jTablePrincipal.getRowCount() > 0) {
            //se a selecionada for diferente de -1  e 0
            if (selecionada != -1 && selecionada != 0) {
                //Foca a barra de rolagem
                jScrollPane1.requestFocus();
                //Seleciona a linha anterior
                jTablePrincipal.setRowSelectionInterval(selecionada - 1, selecionada - 1);
                //Seta a value da barra de rolagem para acompanhar a linha selecionada
                jScrollPane1.getVerticalScrollBar().setValue(jTablePrincipal.getRowHeight() * jTablePrincipal.getSelectedRow());
                jBtPrimeiro.setEnabled(true);
                jBtAnterior.setEnabled(true);
                jBtProximo.setEnabled(true);
                jBtUltimo.setEnabled(true);

                //Se a linha selecionada for igual a zero
            } else if (selecionada == 0) {
                //seta as linhas e a os botoes
                jTablePrincipal.setRowSelectionInterval(0, 0);
                jBtPrimeiro.setEnabled(false);
                jBtAnterior.setEnabled(false);
                jBtProximo.setEnabled(true);
                jBtUltimo.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jBtAnteriorActionPerformed

    private void jBtPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPrimeiroActionPerformed
        //Se o numero de linhas da tabela for 0
        if (jTablePrincipal.getRowCount() > 0) {
            //Foca a barra de rolagem
            jScrollPane1.requestFocus();
            //Foca na tabela
            jTablePrincipal.requestFocus();
            //Seta a value da barra de rolagem para 1
            jScrollPane1.getVerticalScrollBar().setValue(1);
            //seleciona a primeira linha
            jTablePrincipal.addRowSelectionInterval(0, 0);
            //habilita e desablita dos respectivos botões
            jBtPrimeiro.setEnabled(false);
            jBtAnterior.setEnabled(false);
            jBtProximo.setEnabled(true);
            jBtUltimo.setEnabled(true);
        }
    }//GEN-LAST:event_jBtPrimeiroActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        jPnlEdit.setVisible(false);
        jPnlBusca.setVisible(true);
        jFldBusca.requestFocus();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jBtCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtCancelarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jPnlBusca.setVisible(true);
            jPnlEdit.setVisible(false);

        }

        if (evt.getKeyCode() == evt.VK_LEFT) {
            jBtGravar.requestFocus();
        }

        if (evt.getKeyCode() == evt.VK_RIGHT) {
            jFldNomeTerminal.requestFocus();
        }
    }//GEN-LAST:event_jBtCancelarKeyPressed

    private void jBtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGravarActionPerformed
        if (tag_acao == "1" && VerificaField() == true) {
            Inserir(jFldCodigo.getText(), jFldCodTerminal.getText(), jFldNomeTerminal.getText());
        }

        if (tag_acao == "2" && VerificaField() == true) {
            Alterar(jFldCodigo.getText(), jFldCodTerminal.getText(), jFldNomeTerminal.getText());
        }

        if (tag_acao == "3") {
            Deletar(jFldCodigo.getText());
        }
    }//GEN-LAST:event_jBtGravarActionPerformed

    private void jBtGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtGravarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jBtGravar.doClick();
        }

        if (evt.getKeyCode() == evt.VK_RIGHT) {
            jBtCancelar.requestFocus();

        }
    }//GEN-LAST:event_jBtGravarKeyPressed

    private void jFldCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFldCodigoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldCodigoFocusLost

    private void jFldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldCodigoActionPerformed

    private void jFldCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldCodigoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jFldNomeTerminal.requestFocus();
        }
    }//GEN-LAST:event_jFldCodigoKeyPressed

    private void jLabel19KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel19KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19KeyPressed

    private void jFldCodTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFldCodTerminalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldCodTerminalActionPerformed

    private void jFldCodTerminalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldCodTerminalKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jFldNomeTerminal.requestFocus();
        }
    }//GEN-LAST:event_jFldCodTerminalKeyPressed

    private void jFldCodTerminalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldCodTerminalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldCodTerminalKeyReleased

    private void jFldCodTerminalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldCodTerminalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldCodTerminalKeyTyped

    private void jLabel18KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel18KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18KeyPressed

    private void jFldNomeTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFldNomeTerminalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldNomeTerminalActionPerformed

    private void jFldNomeTerminalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldNomeTerminalKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jBtGravar.requestFocus();
        }
    }//GEN-LAST:event_jFldNomeTerminalKeyPressed

    private void jFldNomeTerminalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldNomeTerminalKeyReleased

    }//GEN-LAST:event_jFldNomeTerminalKeyReleased

    private void jFldNomeTerminalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldNomeTerminalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldNomeTerminalKeyTyped

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing

    private void jCmbBxBuscaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbBxBuscaItemStateChanged
        jLblBusca.setText(jCmbBxBusca.getSelectedItem().toString() + ":");
        BuscaParametro(jFldBusca.getText());
    }//GEN-LAST:event_jCmbBxBuscaItemStateChanged

    private void jCmbBxBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBxBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbBxBuscaActionPerformed

    private void jCmbBxBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbBxBuscaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbBxBuscaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTerminalDescarregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTerminalDescarregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTerminalDescarregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTerminalDescarregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTerminalDescarregamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtAnterior;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtGravar;
    private javax.swing.JButton jBtInserir;
    private javax.swing.JButton jBtPrimeiro;
    private javax.swing.JButton jBtProximo;
    private javax.swing.JButton jBtUltimo;
    private javax.swing.JButton jButton10;
    private javax.swing.JComboBox<String> jCmbBxBusca;
    private javax.swing.JComboBox<String> jCmbBxOrdem;
    private javax.swing.JTextField jFldBusca;
    private javax.swing.JTextField jFldCodTerminal;
    private javax.swing.JTextField jFldCodigo;
    private javax.swing.JTextField jFldNomeTerminal;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblAcao;
    private javax.swing.JLabel jLblBusca;
    private javax.swing.JPanel jPnlBotao;
    private javax.swing.JPanel jPnlBusca;
    private javax.swing.JPanel jPnlEdit;
    private javax.swing.JPanel jPnlNorte;
    private javax.swing.JPanel jPnlPrincipal;
    private javax.swing.JPanel jPnlSul;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrincipal;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que define as propriedades do formulario. Ex: Tamanho do jFrame,
     * Localização, cor da tabela, layout das células da tabela, etc...
     */
    public void DefinirFormulario() {
        //permite o jFrame ser redimensionado
        setResizable(true);
        //Define o tamanho minimo tomado pela jinternnalframe
        setMinimumSize(new Dimension(600, 450));
        //Define o tamanho do jFrame
        setSize(600, 450);
        //Define o título do jFrame
        setTitle("Cadastro de Terminal de Descarregamento");

        //CarregaEventojComboBox();
        //setLocationRelativeTo(null);
        //Define o tamanho do jPnlPrincipal
        jPnlPrincipal.setSize(600, 450);
        for (int col = 0; col < jTablePrincipal.getColumnCount(); col++) {
            jTablePrincipal.getColumnModel().getColumn(col).setHeaderRenderer(new MeuRenderizador());
        }
        //Permite que seja selecianada apenas uma linha por vez da jTable
        jTablePrincipal.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Ativa o barra de rolagem horizontal
        jTablePrincipal.setAutoResizeMode(jTablePrincipal.AUTO_RESIZE_OFF);

        centro.setHorizontalAlignment(SwingConstants.CENTER);
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);

        //Define o tamanho das colunas e posicoes das celulas
        jTablePrincipal.getColumnModel().getColumn(0).setMinWidth(90);
        jTablePrincipal.getColumnModel().getColumn(0).setMaxWidth(90);
        jTablePrincipal.getColumnModel().getColumn(0).setCellRenderer(centro);

        jTablePrincipal.getColumnModel().getColumn(1).setMinWidth(200);
        jTablePrincipal.getColumnModel().getColumn(1).setMaxWidth(200);
        jTablePrincipal.getColumnModel().getColumn(1).setCellRenderer(centro);

        jTablePrincipal.getColumnModel().getColumn(2).setMinWidth(450);
        jTablePrincipal.getColumnModel().getColumn(2).setMaxWidth(450);
        jTablePrincipal.getColumnModel().getColumn(2).setCellRenderer(esquerda);
        
        jTablePrincipal.getColumnModel().getColumn(3).setMinWidth(120);
        jTablePrincipal.getColumnModel().getColumn(3).setMaxWidth(120);
        jTablePrincipal.getColumnModel().getColumn(3).setCellRenderer(esquerda);

        jTablePrincipal.getColumnModel().getColumn(4).setMinWidth(120);
        jTablePrincipal.getColumnModel().getColumn(4).setMaxWidth(120);
        jTablePrincipal.getColumnModel().getColumn(4).setCellRenderer(esquerda);

        jTablePrincipal.getColumnModel().getColumn(5).setMinWidth(120);
        jTablePrincipal.getColumnModel().getColumn(5).setMaxWidth(120);
        jTablePrincipal.getColumnModel().getColumn(5).setCellRenderer(esquerda);

        //Seta a tecla de atalho Alt + nos seguntos botoes
        jBtInserir.setMnemonic(KeyEvent.VK_I);
        jBtAlterar.setMnemonic(KeyEvent.VK_A);
        jBtExcluir.setMnemonic(KeyEvent.VK_E);
        jBtGravar.setMnemonic(KeyEvent.VK_G);
        jBtCancelar.setMnemonic(KeyEvent.VK_C);
    }

    /**
     * Método usado para limpar a jTable.
     */
    public void LimpaTabela() {
        DefaultTableModel dtm = (DefaultTableModel) jTablePrincipal.getModel();
        dtm.setNumRows(0);
    }

    /**
     * Método que carrega a lista de dados do banco para mostrar na tabela.
     */
    public void CarregaTudo() {
        try {
            Conectar.ConectarBD();
            LimpaTabela();
            Conectar.result = Conectar.stam.executeQuery("SELECT * FROM MDFE_CAD_TERM_DESCARREG WHERE RGEVENTO <> '3'");
            DefaultTableModel dtm = (DefaultTableModel) jTablePrincipal.getModel();
            while (Conectar.result.next()) {
                dtm.addRow(new Object[]{
                    Conectar.result.getString("CODIGO"),
                    Conectar.result.getString("COD_TERM_DESCARREG"),
                    Conectar.result.getString("NOM_TERM_DESCARREG"),
                    Conectar.result.getString("RGCODUSU"),
                    Conectar.result.getString("RGUSUARIO"),
                    Conectar.result.getDate("RGDATA"),
                    Conectar.result.getString("RGEVENTO")
                });
            }
            Conectar.DesconectarBD();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados na tabela...\n" + e.getLocalizedMessage());
        }
    }

    /**
     * Método que busca os dados na tabela MDFE_CAD_TERM_DESCARREG para enviar para
     * os campos do jPnlEdit a partir do codigo.
     *
     * @param codigo 
     * O código da agência de navegação;
     */
    public void CarregaCampoEdit(String codigo) {
        try {
            Conectar.ConectarBD();
            Conectar.result = Conectar.stam.executeQuery("SELECT * FROM MDFE_CAD_TERM_DESCARREG WHERE CODIGO = '" + codigo + "' ");
            while (Conectar.result.next()) {
                jFldCodigo.setText(Conectar.result.getString("CODIGO"));
                jFldCodTerminal.setText(Conectar.result.getString("COD_TERM_DESCARREG"));
                jFldNomeTerminal.setText(Conectar.result.getString("NOM_TERM_DESCARREG"));
            }
            Conectar.DesconectarBD();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro carregaedit...\n" + e.getLocalizedMessage());
        }
    }

    public void BuscaParametro(String busca) {
        try {

            sql = "";
            if(jCmbBxBusca.getSelectedItem().equals("Código")){
                sql = "WHERE CODIGO like '"+ busca +"%' ";
            }else if(jCmbBxBusca.getSelectedItem().equals("Nome")){
                sql = "WHERE NOME_TERM_DESCARREG like '"+ busca +"%' ";
            }else if(jCmbBxBusca.getSelectedItem().equals("Cod. Terminal")){
                sql = "WHERE COD_TERM_DESCARREG like '"+ busca +"%' ";
            }

            if (jCmbBxOrdem.getSelectedItem().equals("Código")) {
                ordnar = "CODIGO";
            } else if (jCmbBxOrdem.getSelectedItem().equals("Nome")) {
                ordnar = "NOM_TERM_DESCARREG";
            } else if (jCmbBxOrdem.getSelectedItem().equals("Cod. Terminal")) {
                ordnar = "COD_TERM_DESCARREG";
            }

            LimpaTabela();
            Conectar.ConectarBD();
            System.out.println("SELECT * FROM MDFE_CAD_TERM_DESCARREG " + sql + " AND RGEVENTO <> '3'  ORDER BY " + ordnar + " ");
            Conectar.result = Conectar.stam.executeQuery("SELECT * FROM MDFE_CAD_TERM_DESCARREG " + sql + " AND RGEVENTO <> '3' ORDER BY " + ordnar + " ");
            DefaultTableModel dtm = (DefaultTableModel) jTablePrincipal.getModel();
            while (Conectar.result.next()) {
                dtm.addRow(new Object[]{
                    Conectar.result.getString("CODIGO"),
                    Conectar.result.getString("COD_TERM_DESCARREG"),
                    Conectar.result.getString("NOM_TERM_DESCARREG"),
                    Conectar.result.getString("RGCODUSU"),
                    Conectar.result.getString("RGUSUARIO"),
                    Conectar.result.getDate("RGDATA"),
                    Conectar.result.getString("RGEVENTO")
                });
            }

            Conectar.DesconectarBD();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao buscar terminal...\n" + e.getLocalizedMessage());
        }
    }

    /**
     * Método para inserir os dados da agência de navegação na tabela
     * MDFE_CAD_TERM_DESCARREG.
     */
    public void Inserir(String codigo, String codTerm, String nomeTerm) {
        try {
            Conectar.ConectarBD();

            System.out.println("INSERT INTO MDFE_CAD_TERM_DESCARREG (CODIGO, COD_TERM_DESCARREG, NOM_TERM_DESCARREG, "
                    + " RGCODUSU, RGUSUARIO, RGDATA, RGEVENTO)"
                    + " VALUES('" + codigo + "', '" + codTerm + "', '" + nomeTerm + "', "+ tabusu.getCodigo() +", '"+ tabusu.getNome() +"', "
                            + " '"+ util.FormataDataBanco(new Date()) +"', 1 )"
            );

            Conectar.stam.executeUpdate("INSERT INTO MDFE_CAD_TERM_DESCARREG (CODIGO, COD_TERM_DESCARREG, NOM_TERM_DESCARREG, "
                    + " RGCODUSU, RGUSUARIO, RGDATA, RGEVENTO)"
                    + " VALUES('" + codigo + "', '" + codTerm + "', '" + nomeTerm + "', "+ tabusu.getCodigo() +", '"+ tabusu.getNome() +"', "
                            + " '"+ util.FormataDataBanco(new Date()) +"', 1 )"
            );

            jPnlEdit.setVisible(false);
            jPnlBusca.setVisible(true);
            CarregaTudo();
            int resposta = JOptionPane.showConfirmDialog(null, "Registro inserido com sucesso!\n Deseja inserir outro?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                jBtInserir.doClick();
            }else{
                jFldBusca.requestFocus();
            }

            Conectar.DesconectarBD();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao inserir...\n" + e.getLocalizedMessage());
        }
    }

    /**
     * Método para alterar os dados da agência de navegação na tabela
     * MDFE_CAD_TERM_DESCARREG.
     */
    public void Alterar(String codigo, String codTerm, String nomeTerm) {
        try {
            Conectar.ConectarBD();

            System.out.println("UPDATE MDFE_CAD_TERM_DESCARREG SET "
                    + "COD_TERM_DESCARREG = '" + codTerm + "', "
                    + "NOM_TERM_DESCARREG = '" + nomeTerm + "', "
                    + "RGCODUSU           = "+ tabusu.getCodigo() +", "
                    + "RGUSUARIO          = '"+ tabusu.getNome() +"', "
                    + "RGDATA             = '"+ util.FormataData(new Date()) +"', "
                    + "RGEVENTO           = 2 "
                    + "WHERE CODIGO = '" + codigo + "' "
            );

            Conectar.stam.executeUpdate("UPDATE MDFE_CAD_TERM_DESCARREG SET "
                    + "COD_TERM_DESCARREG = '" + codTerm + "', "
                    + "NOM_TERM_DESCARREG = '" + nomeTerm + "', "
                    + "RGCODUSU           = "+ tabusu.getCodigo() +", "
                    + "RGUSUARIO          = '"+ tabusu.getNome() +"', "
                    + "RGDATA             = '"+ util.FormataDataBanco(new Date()) +"', "
                    + "RGEVENTO           = 2 "
                    + "WHERE CODIGO = '" + codigo + "' "
            );

            jPnlEdit.setVisible(false);
            jPnlBusca.setVisible(true);
            CarregaTudo();
            JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
            Conectar.DesconectarBD();
            jFldBusca.requestFocus();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao alterar...\n" + e.getLocalizedMessage());
        }
    }

    /**
     * Método para deletar os dados da agência de navegação na tabela
     * MDFE_CAD_TERM_DESCARREG.
     */
    public void Deletar(String codigo) {
        try {
            Conectar.ConectarBD();

            System.out.println("UPDATE MDFE_CAD_TERM_DESCARREG SET "
                    + "RGCODUSU           = "+ tabusu.getCodigo() +", "
                    + "RGUSUARIO          = '"+ tabusu.getNome() +"', "
                    + "RGDATA             = '"+ util.FormataData(new Date()) +"', "
                    + "RGEVENTO           = 3 "
                    + "WHERE CODIGO = '" + codigo + "' "
            );

            Conectar.stam.executeUpdate("UPDATE MDFE_CAD_TERM_DESCARREG SET "
                    + "RGCODUSU           = "+ tabusu.getCodigo() +", "
                    + "RGUSUARIO          = '"+ tabusu.getNome() +"', "
                    + "RGDATA             = '"+ util.FormataData(new Date()) +"', "
                    + "RGEVENTO           = 3 "
                    + "WHERE CODIGO = '" + codigo + "' "
            );

            jPnlEdit.setVisible(false);
            jPnlBusca.setVisible(true);
            CarregaTudo();
            JOptionPane.showMessageDialog(null, "Deletado com sucesso!");
            Conectar.DesconectarBD();
            jFldBusca.requestFocus();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao deletar...\n" + e.getLocalizedMessage());
        }
    }

    /**
     * Método responsável por incrementar o próximo número do código.
     */
    public void BuscaCodMax() {
        try {
            Conectar.ConectarBD();
            Conectar.result = Conectar.stam.executeQuery("SELECT MAX(CODIGO) + 1 FROM MDFE_CAD_TERM_DESCARREG ");
            while (Conectar.result.next()) {
                if (Conectar.result.getString(1) == null) {
                    codmax = 1;
                } else {
                    codmax = Integer.parseInt(Conectar.result.getString(1));
                }
                jFldCodigo.setText(codmax.toString());
            }
            Conectar.DesconectarBD();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao gerar código...\n" + e.getLocalizedMessage());
        }
    }

    public void LimpaField() {
        jFldCodigo.setText("");
        jFldCodTerminal.setText("");
        jFldNomeTerminal.setText("");
    }
    
    /**
     * Método que verifica se os campos obrigatórios do cadastro foram preechidos 
     * e retorna um valor boolean 'True' se sim e 'False' se não.
    */
    public boolean VerificaField(){
        if(jFldCodTerminal.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Código do Terminal não preenchido!");
            jFldCodTerminal.requestFocus();
            return false;
        }else if(jFldNomeTerminal.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Nome do Terminal não preenchido!");
            jFldNomeTerminal.requestFocus();
            return false;
        }else{
            return true;
        }
    }

    //Evento para sair da tela com a tecla esc
    //Chamar evento no construtor principal da classe
    public void SairEsc() {
        KeyStroke ks = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, true);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(ks, "esc");
        getRootPane().getActionMap().put("esc", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (jPnlBusca.isVisible() == true) {
                    dispose();
                } else if (jPnlEdit.isVisible() == true) {
                    jPnlEdit.setVisible(false);
                    jPnlBusca.setVisible(true);
                    jFldBusca.requestFocus();
                }
            }
        });
    }
    
    /**
     * Classe que implementa o método abstrato TableCellRenderer para poder fazer a troca de cor de fundo e fonte
     * do cabeçalho da tabela. 
     */
    private class MeuRenderizador extends JLabel implements TableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int rowIndex, int vColIndex) {

            table.getTableHeader().setBackground(Color.BLUE);
            table.getTableHeader().setOpaque(false);
            //table.getTableHeader().setFont(new Font("Dialog", 11, Font.BOLD));
            
            setBorder(new LineBorder(Color.WHITE, 1, true));
            setFont(getFont().deriveFont(Font.BOLD));
            setForeground(Color.WHITE);
            setHorizontalAlignment(SwingConstants.LEFT);
            setFont(getFont().deriveFont(Font.BOLD));
            setText(value.toString());

            return this;
        }
    }

}
