/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastro;

import ClassesFirebird.Tabusu;
import ConexaoDB.Conectar;
import Utilitarios.LimitaField;
import Utilitarios.Utilitarios;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;


public class TelaSeguradora extends javax.swing.JInternalFrame {

    public Integer codmax, selecionada;
    String sql, ordnar, situacao, tag_acao;
    DefaultTableCellRenderer direita  = new DefaultTableCellRenderer();
    DefaultTableCellRenderer centro   = new DefaultTableCellRenderer();
    DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
    Utilitarios util                  = new Utilitarios();
    Tabusu tabusu                     = new Tabusu();

    public TelaSeguradora() {
        initComponents();
        DefinirFormulario();
        CarregaTudo();
        SairEsc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlPrincipal = new javax.swing.JPanel();
        jPnlBusca = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCmbBxOrdem = new javax.swing.JComboBox<>();
        jLblBusca = new javax.swing.JLabel();
        jPnlBotao = new javax.swing.JPanel();
        jBtPrimeiro = new javax.swing.JButton();
        jBtAnterior = new javax.swing.JButton();
        jBtProximo = new javax.swing.JButton();
        jBtUltimo = new javax.swing.JButton();
        jBtInserir = new javax.swing.JButton();
        jBtAlterar = new javax.swing.JButton();
        jBtExcluir = new javax.swing.JButton();
        jFldBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrincipal = new javax.swing.JTable();
        jCmbBxBusca = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPnlEdit = new javax.swing.JPanel();
        jPnlNorte = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jFldCodAgNaveg = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jFldCNPJ = new javax.swing.JTextField();
        jFldNomeAgNaveg = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPnlEditBotoes = new javax.swing.JPanel();
        jBtCancelar = new javax.swing.JButton();
        jBtGravar = new javax.swing.JButton();
        jLblAcao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPnlPrincipal.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Buscar por:");

        jCmbBxOrdem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCmbBxOrdem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome" }));
        jCmbBxOrdem.setToolTipText("");
        jCmbBxOrdem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbBxOrdemItemStateChanged(evt);
            }
        });
        jCmbBxOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBxOrdemActionPerformed(evt);
            }
        });
        jCmbBxOrdem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbBxOrdemKeyPressed(evt);
            }
        });

        jLblBusca.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLblBusca.setText("Código:");

        jPnlBotao.setLayout(new java.awt.GridLayout(1, 0));

        jBtPrimeiro.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Primeiro.png"))); // NOI18N
        jBtPrimeiro.setText("Primeiro");
        jBtPrimeiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtPrimeiro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtPrimeiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPrimeiroActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtPrimeiro);

        jBtAnterior.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Anterior.png"))); // NOI18N
        jBtAnterior.setText("Anterior");
        jBtAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtAnterior.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAnteriorActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtAnterior);

        jBtProximo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Proximo.png"))); // NOI18N
        jBtProximo.setText("Próximo");
        jBtProximo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtProximo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtProximo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtProximoActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtProximo);

        jBtUltimo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ultimo.png"))); // NOI18N
        jBtUltimo.setText("Último");
        jBtUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtUltimo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtUltimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtUltimoActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtUltimo);

        jBtInserir.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file_add.png"))); // NOI18N
        jBtInserir.setText("Inserir");
        jBtInserir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtInserir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtInserir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtInserirActionPerformed(evt);
            }
        });
        jBtInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtInserirKeyPressed(evt);
            }
        });
        jPnlBotao.add(jBtInserir);

        jBtAlterar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/text_edit.png"))); // NOI18N
        jBtAlterar.setText("Alterar");
        jBtAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtAlterar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtAlterar);

        jBtExcluir.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/deletar.png"))); // NOI18N
        jBtExcluir.setText("Excluir");
        jBtExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtExcluir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBtExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });
        jPnlBotao.add(jBtExcluir);

        jFldBusca.setDocument(new LimitaField(100, 0)
        );
        jFldBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFldBuscaActionPerformed(evt);
            }
        });
        jFldBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFldBuscaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFldBuscaKeyReleased(evt);
            }
        });

        jTablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Código", "Nome da Seguradora", "CNPJ", "Cód. Usuário", "Usuário", "Data", "Evento"
            }
        ){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            };

        });
        jTablePrincipal.getTableHeader().setResizingAllowed(false);
        jTablePrincipal.getTableHeader().setReorderingAllowed(false);
        jTablePrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePrincipalMouseClicked(evt);
            }
        });
        jTablePrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablePrincipalKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePrincipal);

        jCmbBxBusca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCmbBxBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "CNPJ" }));
        jCmbBxBusca.setToolTipText("");
        jCmbBxBusca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbBxBuscaItemStateChanged(evt);
            }
        });
        jCmbBxBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBxBuscaActionPerformed(evt);
            }
        });
        jCmbBxBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbBxBuscaKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Ordem:");

        javax.swing.GroupLayout jPnlBuscaLayout = new javax.swing.GroupLayout(jPnlBusca);
        jPnlBusca.setLayout(jPnlBuscaLayout);
        jPnlBuscaLayout.setHorizontalGroup(
            jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBuscaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlBuscaLayout.createSequentialGroup()
                        .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbBxBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCmbBxOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addComponent(jPnlBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPnlBuscaLayout.setVerticalGroup(
            jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBuscaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlBuscaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbBxBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbBxOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(jPnlBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPnlPrincipal.add(jPnlBusca, "card2");

        jPnlEdit.setLayout(new java.awt.BorderLayout());

        jPnlNorte.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Código");
        jPnlNorte.add(jLabel4);
        jLabel4.setBounds(10, 0, 34, 30);

        jFldCodAgNaveg.setEditable(false);
        jFldCodAgNaveg.setBackground(new java.awt.Color(255, 255, 204));
        jFldCodAgNaveg.setFocusable(false);
        jFldCodAgNaveg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFldCodAgNavegFocusLost(evt);
            }
        });
        jFldCodAgNaveg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFldCodAgNavegActionPerformed(evt);
            }
        });
        jFldCodAgNaveg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFldCodAgNavegKeyPressed(evt);
            }
        });
        jPnlNorte.add(jFldCodAgNaveg);
        jFldCodAgNaveg.setBounds(10, 20, 90, 25);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("CNPJ");
        jLabel17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel17KeyPressed(evt);
            }
        });
        jPnlNorte.add(jLabel17);
        jLabel17.setBounds(10, 100, 100, 30);

        jFldCNPJ.setDocument(new LimitaField(18, 0)
        );
        jFldCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFldCNPJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFldCNPJFocusLost(evt);
            }
        });
        jFldCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFldCNPJKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFldCNPJKeyPressed(evt);
            }
        });
        jPnlNorte.add(jFldCNPJ);
        jFldCNPJ.setBounds(10, 120, 250, 25);

        jFldNomeAgNaveg.setDocument(new LimitaField(30, 0));
        jFldNomeAgNaveg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFldNomeAgNavegActionPerformed(evt);
            }
        });
        jFldNomeAgNaveg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFldNomeAgNavegKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFldNomeAgNavegKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFldNomeAgNavegKeyReleased(evt);
            }
        });
        jPnlNorte.add(jFldNomeAgNaveg);
        jFldNomeAgNaveg.setBounds(10, 70, 570, 25);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("Nome da Seguradora");
        jLabel18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel18KeyPressed(evt);
            }
        });
        jPnlNorte.add(jLabel18);
        jLabel18.setBounds(10, 50, 130, 30);

        jPnlEdit.add(jPnlNorte, java.awt.BorderLayout.CENTER);

        jPnlEditBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPnlEditBotoes.setPreferredSize(new java.awt.Dimension(0, 60));

        jBtCancelar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtCancelar.setText("Cancelar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });
        jBtCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtCancelarKeyPressed(evt);
            }
        });

        jBtGravar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ok-icon.png"))); // NOI18N
        jBtGravar.setText("Gravar");
        jBtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGravarActionPerformed(evt);
            }
        });
        jBtGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtGravarKeyPressed(evt);
            }
        });

        jLblAcao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblAcao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblAcao.setText("jLabel6");
        jLblAcao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPnlEditBotoesLayout = new javax.swing.GroupLayout(jPnlEditBotoes);
        jPnlEditBotoes.setLayout(jPnlEditBotoesLayout);
        jPnlEditBotoesLayout.setHorizontalGroup(
            jPnlEditBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEditBotoesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jBtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jLblAcao, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addGap(130, 130, 130)
                .addComponent(jBtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPnlEditBotoesLayout.setVerticalGroup(
            jPnlEditBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEditBotoesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPnlEditBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlEditBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblAcao)
                        .addComponent(jBtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );

        jPnlEdit.add(jPnlEditBotoes, java.awt.BorderLayout.SOUTH);

        jPnlPrincipal.add(jPnlEdit, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbBxOrdemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbBxOrdemItemStateChanged
        BuscaParametro(jFldBusca.getText());
    }//GEN-LAST:event_jCmbBxOrdemItemStateChanged

    private void jCmbBxOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBxOrdemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbBxOrdemActionPerformed

    private void jCmbBxOrdemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbBxOrdemKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (jTablePrincipal.getRowCount() > 0) {
                jTablePrincipal.requestFocus();
                jTablePrincipal.addRowSelectionInterval(0, 0);
            } else {
                jBtInserir.requestFocus();
            }
        }
    }//GEN-LAST:event_jCmbBxOrdemKeyPressed

    private void jFldBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFldBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldBuscaActionPerformed

    private void jFldBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldBuscaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jCmbBxBusca.requestFocus();
        }
    }//GEN-LAST:event_jFldBuscaKeyPressed

    private void jFldBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldBuscaKeyReleased

        BuscaParametro(jFldBusca.getText().toUpperCase());
    }//GEN-LAST:event_jFldBuscaKeyReleased

    private void jTablePrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePrincipalMouseClicked
        selecionada = jTablePrincipal.getSelectedRow();
        if (evt.getClickCount() == 2) {
            if (selecionada == -1) {
                return;
            }
            jBtAlterar.doClick();

        }
    }//GEN-LAST:event_jTablePrincipalMouseClicked

    private void jTablePrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablePrincipalKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            selecionada = jTablePrincipal.getSelectedRow();
            jBtAlterar.doClick();
        }
    }//GEN-LAST:event_jTablePrincipalKeyPressed

    private void jBtInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtInserirActionPerformed
        //        if(util.VerificarPermissao("01.01.01", tabusu.getCodigo()) == true){
        tag_acao = "1";
        jLblAcao.setText("Inserir");
        LimpaField();
        BuscaCodMax();
        jPnlBusca.setVisible(false);
        jPnlEdit.setVisible(true);
        jFldNomeAgNaveg.requestFocus();
        //      }else{
        //        JOptionPane.showMessageDialog(null, "Usuário não habilitado para este tipo de operação!");
        //  }

    }//GEN-LAST:event_jBtInserirActionPerformed

    private void jBtInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtInserirKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jBtInserir.doClick();
        }
    }//GEN-LAST:event_jBtInserirKeyPressed

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        //    if(util.VerificarPermissao("01.01.02", tabusu.getCodigo()) == true){
        if (selecionada != -1 && jTablePrincipal.getRowCount() > 0) {
            jLblAcao.setText("Alterar");
            LimpaField();
            jPnlBusca.setVisible(false);
            jPnlEdit.setVisible(true);
            tag_acao = "2";
            CarregaCampoEdit(jTablePrincipal.getValueAt(selecionada, 0).toString());
            jFldNomeAgNaveg.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma agência de navegação selecionada");
        }
        //  }else{
        //    JOptionPane.showMessageDialog(null, "Usuário não habilitado para este tipo de operação!");
        //}

    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        //if (util.VerificarPermissao("01.01.03", tabusu.getCodigo()) == true) {
        if (selecionada != -1 && jTablePrincipal.getRowCount() > 0) {
            jLblAcao.setText("Excluir");
            LimpaField();
            jPnlBusca.setVisible(false);
            jPnlEdit.setVisible(true);
            tag_acao = "3";
            jFldNomeAgNaveg.requestFocus();
            CarregaCampoEdit(jTablePrincipal.getValueAt(selecionada, 0).toString());
            int option = JOptionPane.showConfirmDialog(null, "Confirma Exclusão do Registro", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                jBtGravar.doClick();
            } else if (option == JOptionPane.NO_OPTION) {
                jBtCancelar.doClick();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma agência de navegação selecionada");
        }
        // } else {
        //   JOptionPane.showMessageDialog(null, "Usuário não habilitado para este tipo de operação!");
        //}

    }//GEN-LAST:event_jBtExcluirActionPerformed

    private void jBtUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtUltimoActionPerformed
        selecionada = jTablePrincipal.getSelectedRow();
        //Se o total de linhas da tabela for maior que 0
        if (jTablePrincipal.getRowCount() > 0) {
            //Seleciona a ultima linha
            jTablePrincipal.setRowSelectionInterval(jTablePrincipal.getRowCount() - 1, jTablePrincipal.getRowCount() - 1);
            //Seta a value da barra de rolagem para acompanhar a linha selecionada
            jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
            jBtPrimeiro.setEnabled(true);
            jBtAnterior.setEnabled(true);
            jBtProximo.setEnabled(false);
            jBtUltimo.setEnabled(false);
        }
    }//GEN-LAST:event_jBtUltimoActionPerformed

    private void jBtProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtProximoActionPerformed
        selecionada = jTablePrincipal.getSelectedRow();
        //Se o numeros de linhas da tabela for maior que zero
        if (jTablePrincipal.getRowCount() > 0) {
            //Se a linha selecionada for diferente de -1 e do total de linhas - 1
            if (selecionada != -1 && selecionada != jTablePrincipal.getRowCount() - 1) {
                //Foca na barra de rolagem da tabela
                jScrollPane1.requestFocus();
                //Selecionada a proxima linha
                jTablePrincipal.setRowSelectionInterval(selecionada + 1, selecionada + 1);
                //Seta a value da barra de rolagem para que acompanhe a linha selecionada
                jScrollPane1.getVerticalScrollBar().setValue(jTablePrincipal.getRowHeight() * jTablePrincipal.getSelectedRow());
                jBtPrimeiro.setEnabled(true);
                jBtAnterior.setEnabled(true);
                jBtProximo.setEnabled(true);
                jBtUltimo.setEnabled(true);
                //Se a linha selecionada tiver o mesmo valor do total de linhas da tabela -1
            } else if (selecionada == jTablePrincipal.getRowCount() - 1) {
                //selecionada a ultima linha
                jTablePrincipal.setRowSelectionInterval(jTablePrincipal.getRowCount() - 1, jTablePrincipal.getRowCount() - 1);
                jBtPrimeiro.setEnabled(true);
                jBtAnterior.setEnabled(true);
                jBtProximo.setEnabled(false);
                jBtUltimo.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jBtProximoActionPerformed

    private void jBtAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAnteriorActionPerformed
        selecionada = jTablePrincipal.getSelectedRow();
        //Verifica se a tabela possui mais de 0 linhas
        if (jTablePrincipal.getRowCount() > 0) {
            //se a selecionada for diferente de -1  e 0
            if (selecionada != -1 && selecionada != 0) {
                //Foca a barra de rolagem
                jScrollPane1.requestFocus();
                //Seleciona a linha anterior
                jTablePrincipal.setRowSelectionInterval(selecionada - 1, selecionada - 1);
                //Seta a value da barra de rolagem para acompanhar a linha selecionada
                jScrollPane1.getVerticalScrollBar().setValue(jTablePrincipal.getRowHeight() * jTablePrincipal.getSelectedRow());
                jBtPrimeiro.setEnabled(true);
                jBtAnterior.setEnabled(true);
                jBtProximo.setEnabled(true);
                jBtUltimo.setEnabled(true);

                //Se a linha selecionada for igual a zero
            } else if (selecionada == 0) {
                //seta as linhas e a os botoes
                jTablePrincipal.setRowSelectionInterval(0, 0);
                jBtPrimeiro.setEnabled(false);
                jBtAnterior.setEnabled(false);
                jBtProximo.setEnabled(true);
                jBtUltimo.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jBtAnteriorActionPerformed

    private void jBtPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPrimeiroActionPerformed
        //Se o numero de linhas da tabela for 0
        if (jTablePrincipal.getRowCount() > 0) {
            //Foca a barra de rolagem
            jScrollPane1.requestFocus();
            //Foca na tabela
            jTablePrincipal.requestFocus();
            //Seta a value da barra de rolagem para 1
            jScrollPane1.getVerticalScrollBar().setValue(1);
            //seleciona a primeira linha
            jTablePrincipal.addRowSelectionInterval(0, 0);
            //habilita e desablita dos respectivos botões
            jBtPrimeiro.setEnabled(false);
            jBtAnterior.setEnabled(false);
            jBtProximo.setEnabled(true);
            jBtUltimo.setEnabled(true);
        }
    }//GEN-LAST:event_jBtPrimeiroActionPerformed

    private void jFldCodAgNavegFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFldCodAgNavegFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldCodAgNavegFocusLost

    private void jFldCodAgNavegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFldCodAgNavegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldCodAgNavegActionPerformed

    private void jFldCodAgNavegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldCodAgNavegKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jFldNomeAgNaveg.requestFocus();
        }

    }//GEN-LAST:event_jFldCodAgNavegKeyPressed

    private void jLabel17KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel17KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17KeyPressed

    private void jFldNomeAgNavegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFldNomeAgNavegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldNomeAgNavegActionPerformed

    private void jFldNomeAgNavegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldNomeAgNavegKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jFldCNPJ.requestFocus();
        }
    }//GEN-LAST:event_jFldNomeAgNavegKeyPressed

    private void jFldNomeAgNavegKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldNomeAgNavegKeyReleased

    }//GEN-LAST:event_jFldNomeAgNavegKeyReleased

    private void jFldNomeAgNavegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldNomeAgNavegKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jFldNomeAgNavegKeyTyped

    private void jLabel18KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel18KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18KeyPressed

    private void jFldCNPJKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldCNPJKeyTyped
        String Caracteres = "0123456789";
        if (!Caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jFldCNPJKeyTyped

    private void jFldCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFldCNPJFocusLost
        if (jFldCNPJ.getText().length() > 0) {
            if (util.VerificaCNPJ(jFldCNPJ.getText()) == true) {
                jFldCNPJ.setText(util.FormataCnpj(jFldCNPJ.getText()));
            } else {
                JOptionPane.showMessageDialog(null, "CNPJ Inválido");
                jFldCNPJ.requestFocus();
            }
        }
    }//GEN-LAST:event_jFldCNPJFocusLost

    private void jFldCNPJKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFldCNPJKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jBtGravar.requestFocus();
        }
    }//GEN-LAST:event_jFldCNPJKeyPressed

    private void jFldCNPJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFldCNPJFocusGained
        jFldCNPJ.setText(jFldCNPJ.getText().replaceAll("[/.]", "").replaceAll("-", ""));
    }//GEN-LAST:event_jFldCNPJFocusGained

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jCmbBxBuscaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbBxBuscaItemStateChanged
        jLblBusca.setText(jCmbBxBusca.getSelectedItem().toString());
        BuscaParametro(jFldBusca.getText());
    }//GEN-LAST:event_jCmbBxBuscaItemStateChanged

    private void jCmbBxBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBxBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbBxBuscaActionPerformed

    private void jCmbBxBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbBxBuscaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            jCmbBxOrdem.requestFocus();
        }
    }//GEN-LAST:event_jCmbBxBuscaKeyPressed

    private void jBtGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtGravarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jBtGravar.doClick();
        }

        if (evt.getKeyCode() == evt.VK_RIGHT) {
            jBtCancelar.requestFocus();

        }
    }//GEN-LAST:event_jBtGravarKeyPressed

    private void jBtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGravarActionPerformed
        if (tag_acao == "1" && VerificaField() == true) {
            Inserir(jFldCodAgNaveg.getText(), jFldNomeAgNaveg.getText(), jFldCNPJ.getText().replaceAll("[/-]", "").replaceAll("\\.", ""));
        }

        if (tag_acao == "2" && VerificaField() == true) {
            Alterar(jFldCodAgNaveg.getText(), jFldNomeAgNaveg.getText(), jFldCNPJ.getText().replaceAll("[/-]", "").replaceAll("\\.", ""));
        }

        if (tag_acao == "3" && VerificaField() == true) {
            Deletar(jFldCodAgNaveg.getText());
        }
    }//GEN-LAST:event_jBtGravarActionPerformed

    private void jBtCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtCancelarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jPnlBusca.setVisible(true);
            jPnlEdit.setVisible(false);

        }

        if (evt.getKeyCode() == evt.VK_LEFT) {
            jBtGravar.requestFocus();
        }

        if (evt.getKeyCode() == evt.VK_RIGHT) {
            jFldNomeAgNaveg.requestFocus();
        }
    }//GEN-LAST:event_jBtCancelarKeyPressed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        jPnlEdit.setVisible(false);
        jPnlBusca.setVisible(true);
        jFldBusca.requestFocus();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /**
             *
             */
            UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSeguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSeguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSeguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSeguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSeguradora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtAnterior;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtGravar;
    private javax.swing.JButton jBtInserir;
    private javax.swing.JButton jBtPrimeiro;
    private javax.swing.JButton jBtProximo;
    private javax.swing.JButton jBtUltimo;
    private javax.swing.JComboBox<String> jCmbBxBusca;
    private javax.swing.JComboBox<String> jCmbBxOrdem;
    private javax.swing.JTextField jFldBusca;
    private javax.swing.JTextField jFldCNPJ;
    private javax.swing.JTextField jFldCodAgNaveg;
    private javax.swing.JTextField jFldNomeAgNaveg;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblAcao;
    private javax.swing.JLabel jLblBusca;
    private javax.swing.JPanel jPnlBotao;
    private javax.swing.JPanel jPnlBusca;
    private javax.swing.JPanel jPnlEdit;
    private javax.swing.JPanel jPnlEditBotoes;
    private javax.swing.JPanel jPnlNorte;
    private javax.swing.JPanel jPnlPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrincipal;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que define as propriedades do formulario. Ex: Tamanho do jFrame,
     * Localização, cor da tabela, layout das células da tabela, etc...
     */
    public void DefinirFormulario() {
        
        //Nao permite o jFrame ser redimensionado
        setResizable(true);
        //Define o tamanho minimo do jFrame
        setMinimumSize(new Dimension(600, 450));
        //Define o tamanho do jFrame
        setSize(600, 450);
        //Define o título do jFrame
        setTitle("Cadastro de Seguradoras");

        //setLocationRelativeTo(null);
        //Define o tamanho do jPnlPrincipal
        jPnlPrincipal.setSize(600, 450);
        //Seta a o tamanho e a fonte do cabeçalho da tabela
        jTablePrincipal.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 11));
        //Tira a opacidade
        jTablePrincipal.getTableHeader().setOpaque(false);
        //Seta a cor do foreground para branco
        jTablePrincipal.getTableHeader().setForeground(Color.white);
        
        for (int col = 0; col < jTablePrincipal.getColumnCount(); col++) {
            jTablePrincipal.getColumnModel().getColumn(col).setHeaderRenderer(new MeuRenderizador());
        }

        //Seta a cor do background pata azul
        //jTableAgNaveg.getTableHeader().setBackground(Color.blue);
        //Permite que seja selecianada apenas uma linha por vez da jTable
        jTablePrincipal.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Ativa o barra de rolagem horizontal
        jTablePrincipal.setAutoResizeMode(jTablePrincipal.AUTO_RESIZE_OFF);

        centro.setHorizontalAlignment(SwingConstants.CENTER);
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);

        //Define o tamanho das colunas e posicoes das celulas
        jTablePrincipal.getColumnModel().getColumn(0).setMinWidth(90);
        jTablePrincipal.getColumnModel().getColumn(0).setMaxWidth(90);
        jTablePrincipal.getColumnModel().getColumn(0).setCellRenderer(centro);

        jTablePrincipal.getColumnModel().getColumn(1).setMinWidth(500);
        jTablePrincipal.getColumnModel().getColumn(1).setMaxWidth(500);
        jTablePrincipal.getColumnModel().getColumn(1).setCellRenderer(esquerda);

        jTablePrincipal.getColumnModel().getColumn(2).setMinWidth(200);
        jTablePrincipal.getColumnModel().getColumn(2).setMaxWidth(200);
        jTablePrincipal.getColumnModel().getColumn(2).setCellRenderer(esquerda);
        
        jTablePrincipal.getColumnModel().getColumn(3).setMinWidth(120);
        jTablePrincipal.getColumnModel().getColumn(3).setMaxWidth(120);
        jTablePrincipal.getColumnModel().getColumn(3).setCellRenderer(esquerda);
        
        jTablePrincipal.getColumnModel().getColumn(4).setMinWidth(120);
        jTablePrincipal.getColumnModel().getColumn(4).setMaxWidth(120);
        jTablePrincipal.getColumnModel().getColumn(4).setCellRenderer(esquerda);
        
        jTablePrincipal.getColumnModel().getColumn(5).setMinWidth(120);
        jTablePrincipal.getColumnModel().getColumn(5).setMaxWidth(120);
        jTablePrincipal.getColumnModel().getColumn(5).setCellRenderer(esquerda);
                
        jTablePrincipal.getColumnModel().getColumn(6).setMinWidth(120);
        jTablePrincipal.getColumnModel().getColumn(6).setMaxWidth(120);
        jTablePrincipal.getColumnModel().getColumn(6).setCellRenderer(esquerda);
        

        //Seta a tecla de atalho Alt + nos seguntos botoes
        jBtInserir.setMnemonic(KeyEvent.VK_I);
        jBtAlterar.setMnemonic(KeyEvent.VK_A);
        jBtExcluir.setMnemonic(KeyEvent.VK_E);
        jBtGravar.setMnemonic(KeyEvent.VK_G);
        jBtCancelar.setMnemonic(KeyEvent.VK_C);
    }

    /**
     * Método usado para limpar a jTable.
     */
    public void LimpaTabela() {
        DefaultTableModel dtm = (DefaultTableModel) jTablePrincipal.getModel();
        dtm.setNumRows(0);
    }

    /**
     * Método que carrega a lista de dados do banco para mostrar na tabela.
     */
    public void CarregaTudo() {
        try {
            Conectar.ConectarBD();
            LimpaTabela();
            Conectar.result = Conectar.stam.executeQuery("SELECT * FROM MDFE_CAD_SEGURADORA WHERE RGEVENTO <> '3'");
            DefaultTableModel dtm = (DefaultTableModel) jTablePrincipal.getModel();
            while (Conectar.result.next()) {
                dtm.addRow(new Object[]{
                    Conectar.result.getString("SEG_CODIGO"),
                    Conectar.result.getString("SEG_NOME"),
                    util.FormataCnpj(Conectar.result.getString("SEG_CNPJ")),
                    Conectar.result.getString("RGCODUSU"),
                    Conectar.result.getString("RGUSUARIO"),
                    Conectar.result.getDate("RGDATA"),
                    Conectar.result.getString("RGEVENTO")
                });
            }
            Conectar.DesconectarBD();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados na tabela...\n" + e.getLocalizedMessage());
        }
    }

    /**
     * Método que busca os dados na tabela MDFE_CAD_SEGURADORA para enviar
     * para os campos do jPnlEdit a partir do codigo da agência.
     *
     * @param codAgNaveg O código da agência de navegação;
     */
    public void CarregaCampoEdit(String codAgNaveg) {
        try {
            Conectar.ConectarBD();
            Conectar.result = Conectar.stam.executeQuery("SELECT * FROM MDFE_CAD_SEGURADORA WHERE SEG_CODIGO = '" + codAgNaveg + "' ");
            while (Conectar.result.next()) {
                jFldCodAgNaveg.setText(Conectar.result.getString("SEG_CODIGO"));
                jFldNomeAgNaveg.setText(Conectar.result.getString("SEG_NOME"));
                if(Conectar.result.getString("SEG_CNPJ").length() > 0){
                    jFldCNPJ.setText(util.FormataCnpj(Conectar.result.getString("SEG_CNPJ")));
                }
                
            }
            Conectar.DesconectarBD();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro carregaedit...\n" + e.getLocalizedMessage());
        }
    }

    public void BuscaParametro(String busca) {
        try {
            Conectar.ConectarBD();

            sql = "";
            if(jCmbBxBusca.getSelectedItem().equals("Código")){
                sql = "WHERE SEG_CODIGO like '"+ busca +"%' ";
            }else if(jCmbBxBusca.getSelectedItem().equals("Nome")){
                sql = "WHERE SEG_NOME like '"+ busca +"%' ";
            }else{
                sql = "WHERE SEG_CNPJ like '"+ busca +"%' ";
            }

            if (jCmbBxOrdem.getSelectedItem().equals("Código")) {
                ordnar = "SEG_CODIGO";
            } else if (jCmbBxOrdem.getSelectedItem().equals("Nome")) {
                ordnar = "SEG_NOME";
            }

            LimpaTabela();
            Conectar.ConectarBD();
            System.out.println("SELECT * FROM MDFE_CAD_SEGURADORA " + sql + " AND RGEVENTO <> '3' ORDER BY " + ordnar + " ");
            Conectar.result = Conectar.stam.executeQuery("SELECT * FROM MDFE_CAD_SEGURADORA " + sql + " AND RGEVENTO <> '3' ORDER BY " + ordnar + " ");
            DefaultTableModel dtm = (DefaultTableModel) jTablePrincipal.getModel();
            while (Conectar.result.next()) {
                dtm.addRow(new Object[]{
                    Conectar.result.getString("SEG_CODIGO"),
                    Conectar.result.getString("SEG_NOME"),
                    Conectar.result.getString("SEG_CNPJ"),
                    Conectar.result.getString("RGCODUSU"),
                    Conectar.result.getString("RGUSUARIO"),
                    Conectar.result.getDate("RGDATA"),
                    Conectar.result.getString("RGEVENTO")
                });
            }

            Conectar.DesconectarBD();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao buscar agência...\n" + e.getLocalizedMessage());
        }
    }

    /**
     * Método para inserir os dados da agência de navegação na tabela
     * MDFE_CAD_SEGURADORA.
     */
    public void Inserir(String codSeguradora, String nomeSeguradora, String CNPJ) {
        try {
            Conectar.ConectarBD();

            System.out.println("INSERT INTO MDFE_CAD_SEGURADORA (SEG_CODIGO, SEG_NOME, SEG_CNPJ, RGCODUSU, RGUSUARIO, RGDATA, RGEVENTO )"
                    + " VALUES('" + codSeguradora + "', '" + nomeSeguradora + "', '" + CNPJ + "', " + tabusu.getCodigo() + ", '" + tabusu.getNome() + "', "
                    + " '" + util.FormataDataBanco(new Date()) + "', 1)"
            );

            Conectar.stam.executeUpdate("INSERT INTO MDFE_CAD_SEGURADORA (SEG_CODIGO, SEG_NOME, SEG_CNPJ, RGCODUSU, RGUSUARIO, RGDATA, RGEVENTO )"
                    + " VALUES('" + codSeguradora + "', '" + nomeSeguradora + "', '" + CNPJ + "', " + tabusu.getCodigo() + ", '" + tabusu.getNome() + "', "
                    + " '" + util.FormataDataBanco(new Date()) + "', 1)"
            );

            jPnlEdit.setVisible(false);
            jPnlBusca.setVisible(true);
            CarregaTudo();
            int resposta = JOptionPane.showConfirmDialog(null, "Registro inserido com sucesso!\n Deseja inserir outro?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                jBtInserir.doClick();
            }else{
                jFldBusca.requestFocus();
            }

            Conectar.DesconectarBD();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao inserir...\n" + e.getLocalizedMessage());
        }
    }

    /**
     * Método para alterar os dados da agência de navegação na tabela
     * MDFE_CAD_SEGURADORA.
     */
    public void Alterar(String codSeguradora, String nomeSeguradora, String CNPJ) {
        try {
            Conectar.ConectarBD();

            System.out.println("UPDATE MDFE_CAD_SEGURADORA SET "
                    + "SEG_NOME      = '" + nomeSeguradora + "', "
                    + "SEG_CNPJ      = '" + CNPJ + "', "
                    + "RGCODUSU  = " + tabusu.getCodigo() + ", "
                    + "RGUSUARIO = '" + tabusu.getNome() + "', "
                    + "RGDATA    = '" + util.FormataDataBanco(new Date()) + "', "
                    + "RGEVENTO  = 2"
                    + "WHERE SEG_CODIGO = '" + codSeguradora + "' "
            );

            Conectar.stam.executeUpdate("UPDATE MDFE_CAD_SEGURADORA SET "
                    + "SEG_NOME      = '" + nomeSeguradora + "', "
                    + "SEG_CNPJ      = '" + CNPJ + "', "
                    + "RGCODUSU  = " + tabusu.getCodigo() + ", "
                    + "RGUSUARIO = '" + tabusu.getNome() + "', "
                    + "RGDATA    = '" + util.FormataDataBanco(new Date()) + "', "
                    + "RGEVENTO  = 2"
                    + "WHERE SEG_CODIGO = '" + codSeguradora + "' "
            );

            jPnlEdit.setVisible(false);
            jPnlBusca.setVisible(true);
            CarregaTudo();
            JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
            Conectar.DesconectarBD();
            jFldBusca.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar...\n" + e.getLocalizedMessage());
        }
    }

    /**
     * Método para deletar os dados da agência de navegação na tabela
     * MDFE_CAD_SEGURADORA.
     */
    public void Deletar(String codSeguradora) {
        try {
            Conectar.ConectarBD();

            System.out.println("UPDATE MDFE_CAD_SEGURADORA SET "
                    + "RGCODUSU  = " + tabusu.getCodigo() + ", "
                    + "RGUSUARIO = '" + tabusu.getNome() + "', "
                    + "RGDATA    = '" + util.FormataDataBanco(new Date()) + "', "
                    + "RGEVENTO  = 3"
                    + "WHERE SEG_CODIGO = '" + codSeguradora + "' "
            );

            Conectar.stam.executeUpdate("UPDATE MDFE_CAD_SEGURADORA SET "
                    + "RGCODUSU  = " + tabusu.getCodigo() + ", "
                    + "RGUSUARIO = '" + tabusu.getNome() + "', "
                    + "RGDATA    = '" + util.FormataDataBanco(new Date()) + "', "
                    + "RGEVENTO  = 3"
                    + "WHERE SEG_CODIGO = '" + codSeguradora + "' "
            );

            jPnlEdit.setVisible(false);
            jPnlBusca.setVisible(true);
            CarregaTudo();
            JOptionPane.showMessageDialog(null, "Deletado com sucesso!");
            Conectar.DesconectarBD();
            jFldBusca.requestFocus();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao deletar...\n" + e.getLocalizedMessage());
        }
    }

    /**
     * Método responsável por incrementar o próximo número do código.
     */
    public void BuscaCodMax() {
        try {
            Conectar.ConectarBD();
            Conectar.result = Conectar.stam.executeQuery("SELECT MAX(SEG_CODIGO) + 1 FROM MDFE_CAD_SEGURADORA ");
            while (Conectar.result.next()) {
                if (Conectar.result.getString(1) == null) {
                    codmax = 1;
                } else {
                    codmax = Integer.parseInt(Conectar.result.getString(1));
                }
                
                jFldCodAgNaveg.setText(codmax.toString());
            }
            Conectar.DesconectarBD();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao gerar código...\n" + e.getLocalizedMessage());
        }
    }

    /**
     * Método que verifica se os campos obrigatórios do cadastro foram
     * preechidos e retorna um valor boolean 'True' se sim e 'False' se não.
     */
    public boolean VerificaField() {
        if (jFldNomeAgNaveg.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Nome da Agência não preechido");
            jFldNomeAgNaveg.requestFocus();
            return false;
        } else if (jFldCNPJ.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo CNPJ não preenchido");
            jFldCNPJ.requestFocus();
            return false;
        } else {
            return true;
        }
        
    }

    /**
     * Método para limpar todos o Campos de texto do jPnlEdit.
     */
    public void LimpaField() {
        jFldCodAgNaveg.setText("");
        jFldNomeAgNaveg.setText("");
        jFldCNPJ.setText("");
    }

    //Evento para sair da tela com a tecla esc
    //Chamar evento no construtor principal da classe
    public void SairEsc() {
        KeyStroke ks = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, true);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(ks, "esc");
        getRootPane().getActionMap().put("esc", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (jPnlBusca.isVisible() == true) {
                    dispose();
                } else if (jPnlEdit.isVisible() == true) {
                    jPnlEdit.setVisible(false);
                    jPnlBusca.setVisible(true);
                    jFldBusca.requestFocus();
                }
            }
        });
    }

    /**
     * Classe que implementa o método abstrato TableCellRenderer para poder fazer a troca de cor de fundo e fonte
     * do cabeçalho da tabela. 
     */
    private class MeuRenderizador extends JLabel implements TableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int rowIndex, int vColIndex) {

            table.getTableHeader().setBackground(Color.BLUE);
            table.getTableHeader().setOpaque(false);
            //table.getTableHeader().setFont(new Font("Dialog", 11, Font.BOLD));
            setOpaque(false);
            setBorder(new LineBorder(Color.WHITE, 1, true));
            setForeground(Color.WHITE);
            setFont(getFont().deriveFont(Font.BOLD));
            setHorizontalAlignment(SwingConstants.LEFT);

            setText(value.toString());

            return this;
        }
    }

}
